#!/bin/sh

extraction () {
	# $1: command to extract compress
	# $2: compression name
	# Example: extraction "unzip" "$HOME/filename.zip"
	dirname="$(printf '%s' "$2" | awk -F '/' '{printf $NF}' | awk -F '.' '{print $1}')"
	mkdir -p "$dirname" && cd "$dirname" || exit
	$1 "$2"
	dmenufm
}

case "$1" in
	*.tar.bz2|*.tar.xz|*.tbz2) extraction "tar xvjf" "$1" ;;
	*.tar.gz|*.tgz) extraction "tar xvzf" "$1" ;;
	*.lzma) extraction "unlzma" "$1" ;;
	*.bz2) extraction "bunzip2" "$1" ;;
	*.rar) extraction "unrar x -ad" "$1" ;;
	*.gz) extraction "gunzip" "$1" ;;
	*.tar) tar xvf "$1" ;;
	*.zip) extraction "unzip" "$1" ;;
	*.Z) extraction "uncompress" "$1" ;;
	*.7z) extraction "7z x" "$1" ;;
	*.xz) extraction "unxz" "$1" ;;
	*.exe) extraction "cabextract" "$1" ;;
esac

