#!/bin/sh

extraction () {
	# $1: command to extract compress
	# $2: compression name
	# Example: extraction "unzip" "$HOME/filename.zip"
	dirname="$(printf '%s' "$2" | awk -F '/' '{printf $NF}' | awk -F '.' '{print $1}')"
	mkdir -p "$dirname" && cd "$dirname" || exit
	$1 "$2"
	dmenufm
}

case "$1" in
	*.txt)
		$TERMINAL -e "$EDITOR "$1"" &
		;;
	*.pdf | *.epub)
		zathura "$1" &
		;;
	*.doc | *.docx | *.odt)
		libreoffice "$1" &
		;;
	*.xopp)
		xournalpp "$1" &
		;;
	*.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx | *.as[fx])
		mpv --input-ipc-server=/tmp/mpvsoc$(date +%%s) "$1" 2>/dev/null &
		;;
	*.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus)
		mpv --no-audio-display --input-ipc-server=/tmp/mpvsoc$(date +%%s) "$1" &
		;;
	*.bmp | *.jpg | *.jpeg | *.png | *.ico | *.gif | *.xpm)
		sxiv "$1" &
		;;
	*.svg)
		inkscape "$1" 2>/dev/null &
		;;
	*.xcf)
		gimp "$1" 2>/dev/null &
		;;
	*.csv | *.xls | *.xlsx)
		libreoffice "$1" 2>/dev/null &
		;;
	*.tar.bz2|*.tar.xz|*.tbz2)
		extraction "tar xvjf" "$1"
		;;
	*.tar.gz|*.tgz)
		extraction "tar xvzf" "$1"
		;;
	*.lzma)
		extraction "unlzma" "$1"
		;;
	*.bz2)
		extraction "bunzip2" "$1"
		;;
	*.rar)
		extraction "unrar x -ad" "$1"
		;;
	*.gz)
		extraction "gunzip" "$1"
		;;
	*.tar)
		tar xvf "$1"
		;;
	*.zip)
		extraction "unzip" "$1"
		;;
	*.Z)
		extraction "uncompress" "$1"
		;;
	*.7z)
		extraction "7z x" "$1"
		;;
	*.xz)
		extraction "unxz" "$1"
		;;
	*.exe)
		extraction "cabextract" "$1"
		;;
	*)
		# then try matching by mimetype
		mimetype=$(file -Lb --mime-type "$1")
		case "$mimetype" in
			text/html)
				$BROWSER "$1" &
				;;
			text/* | inode/x-empty | message/rfc822)
				$TERMINAL -e $EDITOR "$1" &
				;;
			inode/directory)
				cd "$1" && $TERMINAL &
				;;
			image/*)
				sxiv "$1" &
				;;
			*)
				xdg-open "$1" &
				;;
		esac
		;;
esac

