#!/bin/sh
# Originally "via-open" in "xalexalex/via"

case "$1" in
	*.txt)
		$TERMINAL -e "$EDITOR "$1"" &
		;;
	*.pdf | *.epub)
		zathura "$1" &
		;;
	*.doc | *.docx | *.odt)
		abiword "$1" &
		;;
	*.xopp)
		xournalpp "$1" &
		;;
	*.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx | *.as[fx])
		mpv --input-ipc-server=/tmp/mpvsoc$(date +%%s) "$1" 2>/dev/null &
		;;
	*.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus)
		mpv --no-audio-display --input-ipc-server=/tmp/mpvsoc$(date +%%s) "$1" &
		;;
	*.bmp | *.jpg | *.jpeg | *.png | *.ico | *.gif | *.xpm)
		sxiv "$1" &
		;;
	*.svg)
		inkscape "$1" 2>/dev/null &
		;;
	*.xcf)
		gimp "$1" 2>/dev/null &
		;;
	*.csv | *.xls | *.xlsx)
		sc-im "$1" 2>/dev/null &
		;;
	*)
		# then try matching by mimetype
		mimetype=$(file -Lb --mime-type "$1")
		case "$mimetype" in
			text/html)
				$BROWSER "$1" &
				;;
			text/* | inode/x-empty | message/rfc822)
				$TERMINAL -e "$EDITOR "$1"" &
				;;
			inode/directory)
				# cd "$1" && $TERMINAL &
				cd "$1" && $TERMINAL -e "$FILE" && cd - &
				;;
			image/*)
				sxiv "$1" &
				;;
			*)
				exit 1
				;;
		esac
		;;
esac

