#!/bin/sh

DangerMenu () { # Usage: DangerMenu [CMD] [MSG] [Dest]
	IFS="
	"
	if DangerPrompt "$2"; then
		for selection in $(printf '%s' "$SELECTED"); do
			unset IFS
			if [ -z "$destination" ]; then
				$1 "$selection"
			else
				$1 "$selection" "$3"
			fi
		done && NotiPrompt "Selected removed."
	fi
}

FM_DEL () {
	# Allow multiple files to be selected
	allowbulk="Bulk Delete"
	allselection="Bulk Delete all"
	# Choose file/directory in current directory to remove
	ActionMenu "Remove file / directory: " "$FM_ACTION_COLOR_LV1" || return && allowbulk="NotAllowed"
	if [ -n "$bulkselection" ]; then
		# Multi-selection mode
		BulkMode "Select files / directories to delete: " [ "$actCHOICE" = "$ENDSELECTION" ] && DangerMenu "rm -rf" "Delete all selected?" ""
	elif [ "$actCHOICE" = "$allselection" ]; then
		BulkListAll
		DangerMenu "rm -rf" "Delete all selected in $name?" ""
	else
		# Single-selection mode
		allowbulk="NotAllowed"
		# Check the chosen on is directory or not
		[ -n "$HERE" ] && [ -d "$HERE" ] && result=$?
		[ -n "$HERE" ] && SELECTED="$HERE" && DangerMenu "rm -rf" "Remove all the files / directories in $name?" ""
		[ "$result" = "0" ] && cd "../" && result=
	fi
}
