#!/bin/sh

BulkListAll () {
	SELECTED=$(printf '%s' "$list" \
		| sed "/^$/ d; s=^=$PWD/=g")
	[ -n "$SELECTED" ] \
		&& printf '%s' "$SELECTED" \
		| yprompt "Selected files (Enter to continue): " "$FM_ACTION_COLOR_LV1"
}

BulkMode () { # Usage: BulkMode [MSG]
	HERE=
	bulklist=
	ActionMenu "$1" "$FM_ACTION_COLOR_BULK" \
		|| return && allowbulk="NotAllowed"
	while [ -n "$bulkselection" ]; do
		ActionMenu "$1" "$FM_ACTION_COLOR_BULK" \
			|| return && allowbulk="NotAllowed"
		HERE=$bulklist
		allowbulk="NotAllowed"
	done

	SELECTED=$(printf '%s' "$HERE" | uniq)
	allowbulk="NotAllowed"

	[ "$actCHOICE" = "$ENDSELECTION" ] \
		&& printf '%s' "$SELECTED" \
		| sed "/^$/ d" \
		| yprompt "Selected files (Enter to continue): " \
		"$FM_ACTION_COLOR_LV1"
}

FM_Action () {
	move=$(printf '%s\n' "$ACTLIST" | yprompt "Actions:" "$FM_GENERIC_COLOR")
	case $move in
		"$FM_PCP") FM_PCP ;;
		"$FM_NEW") FM_NEW ;;
		"$FM_MVV"|"$FM_YAK"|"$FM_LNK") FM_MYL ;;
		"$FM_ZIP") FM_ZIP ;;
		"$FM_REM") FM_REM ;;
		"$FM_DEL") FM_DEL ;;
		"$FM_TRH") FM_TRH ;;
		"$FM_HIS") FM_HIS ;;
		"$FM_BMK") FM_BMK ;;
		"$FM_CMD") FM_CMD ;;
	esac
	MainMenu
}
