#!/bin/sh

BulkCMD () {
	execfile=$(printf '%s' "$SELECTED")
	execmd=$(printf '%s' "$execmd" | sed "1 s/$.*//")
	IFS="
	"
	for selection in $(printf '%s' "$execfile"); do
		unset IFS
		$execmd "$selection"
	done && NotiPrompt "Command executed on selected."
}

ExecCMD () { # Usage ExecCMD [CMD]
	software=$(printf '%s' "${1%% *}")
	appdesktop=$(find "$XDGDIR1" "$XDGDIR2" -name "*$software*.desktop" | tail -n 1)
	if [ -n "$appdesktop" ] && grep 'Terminal=false' "$appdesktop"; then
		printf '%s' "$1" | ${SHELL:-"/bin/sh"}
	else
		$TERMINAL -e $1 | ${SHELL:-"/bin/sh"}
	fi
}

FM_CMD () {
	cmdmenu=$(printf '%s\n' "$(cat -u "$FM_CMDFILE")" \
	"Add CMD" "Delete CMD" | yprompt "Dmenufm Custom Command" "$FM_GENERIC_COLOR")
		case "$cmdmenu" in
			"Add CMD")
				addcmd=$(xprompt "Recording your command: " "$FM_ACTION_COLOR_LV1") || return
				desp=$(xprompt "Enter command description: " "$FM_ACTION_COLOR_LV1") || return
				[ -n "$addcmd" ] && printf '%s\n' "$addcmd - $desp" >> "$FM_CMDFILE"
				[ -n "$addcmd" ]  && sed "/^$/ d" "$FM_CMDFILE"  > "$FM_CMDFILE.backup"  && cp "$FM_CMDFILE.backup" "$FM_CMDFILE"
				;;
			"Delete CMD")
				delcmd=$(< "$FM_CMDFILE" yprompt "Delete chosen command: " "darkred")
				# POSIX way of sed -i.
				# Assign address as '+' by '\+pattern+'
				# '=' seems not usable in command
				# Create backup file and cp to original file.
				[ -n "$delcmd" ] && sed "\:$delcmd: d" "$FM_CMDFILE" > "$FM_CMDFILE.backup" && cp "$FM_CMDFILE.backup" "$FM_CMDFILE"
				;;
			*)
				execmd=${cmdmenu%% - *}
				if printf '%s' "$execmd" | grep '\$'; then
					allowbulk="Bulk Execute"
					allselection="Bulk Execute all"
					ActionMenu "Choose and execute: " "$FM_ACTION_COLOR_LV1"
					if [ -n "$bulkselection" ]; then
						BulkMode "Select to execute: "
						BulkCMD
					elif [ "$actCHOICE" = "$allselection" ]; then
						BulkListAll
						BulkCMD
					else
						SELECTED="$HERE"
						BulkCMD
					fi
				else
					ExecCMD "$execmd"
				fi
				;;
		esac
}
