#!/bin/sh

# Store every move between directories into history
History () {
	[ ! -d "$FM_PATH" ] && mkdir -p "$FM_PATH"
	dirmark="${PWD##*/}"
	printf '%s\n' "$dirmark - $PWD" | sed "/^$/ d" >> "$FM_HISFILE"
	# Limit the max number of history
	TMP=$(wc -l "$FM_HISFILE")
	hisnum=${TMP%% *}
	unset TMP
	[ "$hisnum" -ge "$FM_MAX_HIS_LENGTH" ] && sed "1d" "$FM_HISFILE" > "$FM_HISFILE.backup" && cp "$FM_HISFILE.backup" "$FM_HISFILE"
}

FM_HIS () {
	# Use sed command to mimic reverse of cat for POSIX.
	goto=$(sed '1!G;h;$!d' "$FM_HISFILE" | yprompt "Dmenufm History" "$FM_GENERIC_COLOR")
	destination=${goto##* - }
	cd "$destination" || return
}
