#!/bin/sh

# Bulk compression
BulkCompress () {
	case $compression_type in
		"tar.gz") cmd="tar -czvf" ;;
		"tar.xz") cmd="tar -cJvf" ;;
		"tar.bz2") cmd="tar -cjvf" ;;
		"gz") cmd="gzip -k" ;;
		"bz2") cmd="bzip2 -k" ;;
		"xz") cmd="xz -k" ;;
		"lzma") cmd="lzma -k" ;;
		"7z") cmd="7z a" ;;
		"zip") cmd="zip -r" ;;
		*) return ;;
	esac
	if echo "$compression_type" | grep -E '^tar|^zip'; then
		[ -d "$FM_ZIPATH" ] && rm -rf "$FM_ZIPATH"
		mkdir "$FM_ZIPATH"
		IFS="
		"
		for file in $SELECTED; do
			unset IFS
			cp -R "$file" "$FM_ZIPATH"
		done
		archive_name=$(xprompt "Please insert archive name: " "$FM_ACTION_COLOR_LV2" | cut -d'.' -f1) || return
		if [ -n "$archive_name" ]; then
			compressdir_name="$archive_name"
			archive_name="$archive_name.$compression_type"
			mv "$FM_ZIPATH" "./$compressdir_name"
			$cmd "$archive_name" ./"$compressdir_name"/* && NotiPrompt "Compressed to $archive_name"
			rm -rf ./"$compressdir_name"
		fi
	else
		IFS="
		"
		for file in $SELECTED; do
			unset IFS
			$cmd "$file" && NotiPrompt "Compressed to ${file##*/}"
		done
	fi
	## TODO: Add error handling
}


FM_ZIP () {
	allowbulk="Bulk Compress"
	allselection="Bulk Compress all"
	compression_type=$(printf '%s\n' "$COMPRESSIONLIST" | yprompt "Compression type: " "$FM_ACTION_COLOR_LV1" || return && allowbulk="NotAllowed")
	if ! printf '%s' "$compression_type" | grep -E '^tar|^zip'; then
		allowbulk="NotAllowed"
	fi
	[ -n "$compression_type" ] && ActionMenu "Source: " "$FM_ACTION_COLOR_LV1" || return && allowbulk="NotAllowed"
	if [ -n "$bulkselection" ]; then
		BulkMode "Select files / directories to compress: "
		[ "$actCHOICE" = "$ENDSELECTION" ] && BulkCompress
	elif [ "$actCHOICE" = "$allselection" ]; then
		BulkListAll
		BulkCompress
	else
		SELECTED="$HERE"
		[ -n "$SELECTED" ] && BulkCompress
	fi
}
